
import { InventoryItem, Category, ItemStatus } from '../types';

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'item-1',
    name: 'Laptop Dell XPS 15',
    serialNumber: 'DXPS15-12345',
    category: Category.ELEKTRONIK,
    purchaseDate: '2023-05-10',
    price: 25000000,
    location: 'Departemen IT',
    assignedTo: 'Andi Wijaya',
    status: ItemStatus.BAIK,
    description: 'Laptop performa tinggi untuk development.',
    imageUrl: 'https://picsum.photos/seed/laptop/400/300',
  },
  {
    id: 'item-2',
    name: 'Meja Kerja Ergonomis',
    serialNumber: 'MJE-007',
    category: Category.FURNITUR,
    purchaseDate: '2022-11-20',
    price: 3500000,
    location: 'Ruang Kerja Terbuka',
    assignedTo: 'Siti Aminah',
    status: ItemStatus.BAIK,
    description: 'Meja dengan pengaturan ketinggian elektrik.',
    imageUrl: 'https://picsum.photos/seed/desk/400/300',
  },
  {
    id: 'item-3',
    name: 'Proyektor Epson EB-X400',
    serialNumber: 'EPS-X400-9876',
    category: Category.ELEKTRONIK,
    purchaseDate: '2023-01-15',
    price: 8000000,
    location: 'Ruang Rapat A',
    assignedTo: 'Umum',
    status: ItemStatus.DIPINJAM,
    description: 'Proyektor untuk kebutuhan presentasi.',
    imageUrl: 'https://picsum.photos/seed/projector/400/300',
  },
  {
    id: 'item-4',
    name: 'Kursi Kantor Herman Miller',
    serialNumber: 'KHM-Aeron-012',
    category: Category.FURNITUR,
    purchaseDate: '2022-11-20',
    price: 15000000,
    location: 'Departemen Desain',
    assignedTo: 'Budi Santoso',
    status: ItemStatus.RUSAK_RINGAN,
    description: 'Sandaran tangan sedikit goyang.',
    imageUrl: 'https://picsum.photos/seed/chair/400/300',
  },
  {
    id: 'item-5',
    name: 'Printer HP LaserJet Pro',
    serialNumber: 'HPLJP-M404DN-555',
    category: Category.ELEKTRONIK,
    purchaseDate: '2023-08-01',
    price: 6500000,
    location: 'Pantry Lt. 2',
    assignedTo: 'Umum',
    status: ItemStatus.PERLU_PERBAIKAN,
    description: 'Toner habis dan sering paper jam.',
    imageUrl: 'https://picsum.photos/seed/printer/400/300',
  },
   {
    id: 'item-6',
    name: 'Stok Kertas A4',
    serialNumber: 'ATK-KRT-A4-RIM',
    category: Category.ATK,
    purchaseDate: '2024-03-01',
    price: 50000,
    location: 'Gudang ATK',
    assignedTo: 'Admin',
    status: ItemStatus.BAIK,
    description: 'Kertas HVS A4 80 gsm per rim.',
    imageUrl: 'https://picsum.photos/seed/paper/400/300',
  },
];
